### ISSUE TITLE
Installing ROOT on OS X 10.11

### ISSUE THREAD

**Issue by alexpearce** [alexpearce/alexpearce.github.com#25]
Comment thread for post [Installing ROOT on OS X 10.11](https://alexpearce.me/2016/02/root-on-os-x-el-capitan/).

Comments made before 18 February 2021 were imported from Disqus using an [import script](https://gist.github.com/alexpearce/ff0b5e9f1c0816d7009985dfa0dcaa19). The datetimes and authors of the imported comments do not reflect the values of the original comments.

**Comment by alexpearce** [comment]
_Comment № 1 originally by Timon at 2016-02-10 12:10:02 UTC_.

Hi Alex,

thanks for this guide! Unfortunately my pyroot is not working if I install root the way you described it.

 Fatal Python error: PyThreadState\_Get: no current thread

Is there anything I need to change while installing? (Btw: I am using Anaconda python. Maybe this could also be the reason?)

**Comment by alexpearce** [comment]
_Comment № 2 originally by Alex Pearce at 2016-02-14 17:47:27 UTC, replying to [a comment by Timon at 2016-02-10 12:10:02 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514304)_.

Hi Timon. Having an Anaconda install is almost certainly the reason.

I think what happens is that ROOT is compiled with either the system Python (that comes with OS X) or the Homebrew Python, but then when you do import ROOT inside a python session, it's the Anaconda Python you're using, so ROOT doesn't work.

You can test this by temporarily removing the path to Anaconda from your PATH, or by explicitly using the system Python. These three lines will try the three different versions:

$ python -c 'import ROOT' # Anaconda Python, should fail  
$ /usr/bin/python -c 'import ROOT' # System Python  
$ /usr/local/bin/python -c 'import ROOT' # Homebrew PythonYou can have Anaconda installed, but when you want to use ROOT you can't use the Anaconda python.

One solution would be to install ROOT as a Conda package. I don't have any experience with that, but there are [ROOT 6 Conda recipes by remenska](https://github.com/remenska/root-conda-recipes "https://github.com/remenska/root-conda-recipes").

**Comment by alexpearce** [comment]
_Comment № 3 originally by Vlad Lyalin at 2016-03-08 15:52:39 UTC_.

Hello Alex,

Thank you very much for this guide!  
Could you tell, is it possible to use pyROOT and PyCharm IDE if ROOT is installed via homebrew?

**Comment by alexpearce** [comment]
_Comment № 4 originally by Alex Pearce at 2016-03-08 15:53:55 UTC, replying to [a comment by Vlad Lyalin at 2016-03-08 15:52:39 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514355)_.

Hi Влад,

You can definitely use PyROOT. I'm not familiar with PyCharm, but it should work!

**Comment by alexpearce** [comment]
_Comment № 5 originally by Vlad Lyalin at 2016-03-08 20:56:35 UTC, replying to [a comment by Alex Pearce at 2016-03-08 15:53:55 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514383)_.

Yep, it should work, but it isn't ((  
ImportError: No module named ROOT  
As I understand, the issue is when we start new terminal window this line of code  
. $(brew --prefix root6)/libexec/[thisroot.sh](http://thisroot.sh "thisroot.sh")  
is executed, but PyCharm doesn't do that... How to fix this?  
P.S. This is not an interpretator problem, I've already tried build-in OS X python and homebred-installed python as project interpretator - both doesn't work.

**Comment by alexpearce** [comment]
_Comment № 6 originally by Alex Pearce at 2016-03-08 21:12:20 UTC, replying to [a comment by Vlad Lyalin at 2016-03-08 20:56:35 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514406)_.

So, import ROOT doesn't worked even after running . $(brew --prefix root6)/libexec/thisroot.sh? If so, that's strange.

If not, then you just need to tell PyCharm to execute that line. If you put that line in your .bashrc then it might just work after a restart, else you might need to [change the default shell](http://stackoverflow.com/a/31052534/596068 "http://stackoverflow.com/a/31052534/596068").

**Comment by alexpearce** [comment]
_Comment № 7 originally by Vlad Lyalin at 2016-03-09 11:46:56 UTC, replying to [a comment by Alex Pearce at 2016-03-08 21:12:20 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514436)_.

The problem was in $PYTHONPATH - it wasn't set within the PyCharm.  
I added   
/usr/local/Cellar/root/5.34.34\_1/lib/root  
to the Project Structure and it worked.

**Comment by alexpearce** [comment]
_Comment № 8 originally by Mehul at 2016-03-15 06:48:12 UTC_.

Hi Alex

I want to install root v6-07-04. This installs v6-06. How do I make the change?

**Comment by alexpearce** [comment]
_Comment № 9 originally by Alex Pearce at 2016-03-17 10:28:55 UTC, replying to [a comment by Mehul at 2016-03-15 06:48:12 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514490)_.

Hi Mehul.

What version of ROOT to build is defined in the [ROOT 6 formula](https://github.com/Homebrew/homebrew-science/blob/master/root6.rb "https://github.com/Homebrew/homebrew-science/blob/master/root6.rb"). You can edit this formula to specify a different version, bearing in mind that you will also need to change the sha256 attribute to match that of the 6.07.04 tarball.

You can edit the formula on your machine with  


$ brew edit root6  
Make your changes, save the file, then try brew install root6 again (you may need to brew uninstall root6 beforehand).

Note that the install will take much longer now, because Homebrew will compile ROOT on your machine. When you use the version defined by Homebrew (6.06.00 in your case), Homebrew downloads a precompiled version and uses that, taking much less time.

**Comment by alexpearce** [comment]
_Comment № 10 originally by Mehul at 2016-03-17 12:36:09 UTC, replying to [a comment by Alex Pearce at 2016-03-17 10:28:55 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514521)_.

Hi Alex

I made these changes in version number and sha. I am facing two problems now:  
1. The version I need is available only via git   
2. I tried building the repository obtained by git clone. The build is giving me a linker error saying libclingJupyter library is not found.

I installed v6-06 using homebrew and tried going ahead with v6-06 to run a notebook file I had. When I try to run the python script, it says 'ROOT module not found'. I have made the changes in the path to the ROOTSYS and PYTHONDIR but the problem persists!   
I'm really clueless as to how I should proceed now.

What are your thoughts on this?

Thanks and Regards  
Mehul

**Comment by alexpearce** [comment]
_Comment № 11 originally by Alex Pearce at 2016-03-18 00:05:17 UTC, replying to [a comment by Mehul at 2016-03-17 12:36:09 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514548)_.

Shouldn't it be PYTHONPATH that you need to update, rather than PYTHONDIR?

**Comment by alexpearce** [comment]
_Comment № 12 originally by Talal at 2016-03-23 17:02:47 UTC_.

Hi Alex,

I have ROOT 5.34.34 and I noticed that it didn't have FFTW dependency so I installed FFTW and then reinstalled ROOT (--with-fftw) (via Homebrew) but when trying to compile a macro that require FFTW I get the following:

Error in <tmacosxsystem::dynamicpathname>: FFTW[.so | .dll | .dylib | .sl | .dl | .a] does not exist in .:/usr/local/Cellar/root/5.34.34\_1/lib/root::/usr/local/Cellar/root/5.34.34\_1/lib/root/cint/cint/stl

Error in <tvirtualfft::fft>: handler not found

I'm guessing there's a missing file in the root directory. Any idea how to sort this out?

Thanks,  
Talal

**Comment by alexpearce** [comment]
_Comment № 13 originally by Darius at 2016-06-07 18:09:05 UTC_.

Really nice from you to display this information !   
I just began an internship and was willing to install root on my mac. A guy from my team told me installing root on a mac was going to be really hard. But apparently, not anymore ! Thanks for the time you spare me !

**Comment by alexpearce** [comment]
_Comment № 14 originally by Alex Pearce at 2016-06-07 18:18:31 UTC, replying to [a comment by Talal at 2016-03-23 17:02:47 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514598)_.

Hi Talal. I haven't installed ROOT 5 in a long time, and never with the FFTW library, so I'm not sure what's going wrong here. You could open an issue on the [Homebrew science GitHub repository](https://github.com/Homebrew/homebrew-science "https://github.com/Homebrew/homebrew-science"), where the [ROOT 5 formula](https://github.com/Homebrew/homebrew-science/blob/master/root.rb "https://github.com/Homebrew/homebrew-science/blob/master/root.rb") is maintained. Someone there might be able to help.

**Comment by alexpearce** [comment]
_Comment № 15 originally by Alex Pearce at 2016-06-17 20:37:22 UTC, replying to a since-deleted comment_.

Hi Wei. Homebrew won't let you install conflicting formulae. Both the root and root6 formulae install the root binary, and so cannot be installed at the same time. If you want to install ROOT 6, you need to remove 5.

And yes, the dot is required. I believe it's equivalent to using source.

**Comment by alexpearce** [comment]
_Comment № 16 originally by Sven Vahsen at 2016-08-04 21:54:59 UTC_.

Dear Alex,

Thank you for wonderful guide. Being a recent Mac convert, you allowed me to setup get started with root on my new machine in a matter of minutes.

There is one part of my root install that does not seem to work on Mac, however, and that is the Open GL viewer. For instance, when I install root 5.34.34 with homebrew, and then try to run the standard root tutorial "lego", I get the output below my signature.

Any ideas of what I could try? Basically I have no idea whether this is a setup problem, mac specific, or due to the home-brew install.

Would be thankful for any pointers.

Best regards,  
Sven

-----  
>.x lego.C

[non-error output surpressed]

Error in <tmacosxsystem::dynamicpathname>: RGL[.so | .dll | .dylib | .sl | .dl | .a] does not exist in /usr/local/Cellar/root/5.34.34\_1/lib/root:/usr/local/Cellar/root/5.34.34\_1/lib/root::.:/usr/local/Cellar/root/5.34.34\_1/lib/root::/usr/local/Cellar/root/5.34.34\_1/lib/root/cint/cint/stl

Warning in <tcanvas::tpad::createviewer3d>: Cannot create 3D viewer of type: ogl

**Comment by alexpearce** [comment]
_Comment № 17 originally by Alex Pearce at 2016-08-05 09:06:11 UTC, replying to [a comment by Sven Vahsen at 2016-08-04 21:54:59 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514709)_.

Hi Sven. I tried running that file and it worked; I didn't see the error message you do. After some Googling, [some people think](http://stackoverflow.com/questions/33634871/installing-rgl-package-in-r-mac-osx-el-captian-fixed "http://stackoverflow.com/questions/33634871/installing-rgl-package-in-r-mac-osx-el-captian-fixed") that [installing XQuartz](https://www.xquartz.org/ "https://www.xquartz.org/") fixes the problem, so I would try that first. (You will need to log out and then log in after installing it.)

Most of the ROOT GUI stuff doesn't need XQuartz, it uses a native Cocoa backend, so you don't need to install it when installing ROOT. But apparently some parts of ROOT still require it.

**Comment by alexpearce** [comment]
_Comment № 18 originally by Hosein Hashemi at 2016-08-19 09:26:04 UTC, replying to [a comment by Alex Pearce at 2016-02-14 17:47:27 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514326)_.

Hello Alex,  
I have the same problem with pyROOT.   
this is my .bashrc:

# Setting PATH for Python 3.5  
# The orginal version is saved in .bash\_profile.pysave  
PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"  
export PATH

# added by Anaconda3 4.0.0 installer  
export PATH="/Users/Psychology/anaconda/bin:$PATH"

# added by Anaconda3 4.0.0 installer  
export PATH="/Users/Psychology/anaconda/bin:$PATH"

# Setting PATH for Python 3.5  
# The orginal version is saved in .bash\_profile.pysave  
PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"  
export PATH

# added by Anaconda3 4.0.0 installer  
export PATH="/Users/Psychology/anaconda3/bin:$PATH"  
export LANG="it\_IT.UTF-8"  
export LC\_COLLATE="it\_IT.UTF-8"   
export LC\_CTYPE="it\_IT.UTF-8"   
export LC\_MESSAGES="it\_IT.UTF-8"   
export LC\_MONETARY="it\_IT.UTF-8"   
export LC\_NUMERIC="it\_IT.UTF-8"   
export LC\_TIME="it\_IT.UTF-8"   
export LC\_ALL=

#  
export PATH=$ROOTSYS/bin:$PYTHONDIR/bin:$PATH  
export LD\_LIBRARY\_PATH=$ROOTSYS/lib:$PYTHONDIR/lib:$LD\_LIBRARY\_PATH  
export PYTHONPATH=$ROOTSYS/lib:$PYTHONPATH

I dont know what to do, I would be very grateful if you help me.

**Comment by alexpearce** [comment]
_Comment № 19 originally by Alex Pearce at 2016-08-19 09:37:13 UTC, replying to [a comment by Hosein Hashemi at 2016-08-19 09:26:04 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514764)_.

Have you tried the commands in my comment?

**Comment by alexpearce** [comment]
_Comment № 20 originally by Hosein Hashemi at 2016-08-19 09:50:40 UTC, replying to [a comment by Alex Pearce at 2016-08-19 09:37:13 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514796)_.

Yes, I did.  
Hosein:~ Psychology$ python -c 'import ROOT'  
Traceback (most recent call last):  
 File "<string>", line 1, in <module>  
ImportError: No module named 'ROOT'  
Hosein:~ Psychology$ /usr/bin/python -c 'import ROOT'  
Traceback (most recent call last):  
 File "<string>", line 1, in <module>  
ImportError: No module named ROOT  
Hosein:~ Psychology$ /usr/local/bin/python -c 'import ROOT'  
-bash: /usr/local/bin/python: No such file or directory  
Hosein:~ Psychology$

**Comment by alexpearce** [comment]
_Comment № 21 originally by Alex Pearce at 2016-08-19 10:49:56 UTC, replying to [a comment by Hosein Hashemi at 2016-08-19 09:50:40 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514822)_.

Ah, you don't have Python installed via Homebrew, I guess you installed in using one the packages from the official Python site.

You can see which Python ROOT was compiled with by running:

  
$ root-config --config  
That will contain a PYTHON\_INCLUDE\_DIR variable. You should poke around directories there to find the bin/ folder, and try to run the commands using that Python to check.

The problem is still, I think, that your default Python, when you run the python command, isn't the same one as the one ROOT was compiled against.

**Comment by alexpearce** [comment]
_Comment № 22 originally by Carlos at 2016-10-20 00:08:44 UTC_.

Hi Alex,

Thank you for the amazing guide!

I recently made the mistake of upgrading my OS X from El Capitan to Sierra, and now I am having a lot of problems with my code. I am currently using root 5.34 and so, in an attempt to get my code to work, I tried installing root6 instead. Unfortunately, when I try to do this I get the following warning:

Warning: You are using OS X 10.12.  
We do not provide support for this pre-release version.  
You may encounter build failures or other breakages.  
Please create pull-requests instead of filing issues.

Do you know if there is any root version that supports Sierra? If not, do you know a way of working around these compatibility issues? I would prefer not to downgrade back to El Capitan unless it's the only option.

Thanks!

**Comment by alexpearce** [comment]
_Comment № 23 originally by Alex Pearce at 2016-10-20 05:56:07 UTC, replying to [a comment by Carlos at 2016-10-20 00:08:44 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514884)_.

Thanks Carlos.

As far as I know, Sierra <emph>is</emph> supported by ROOT. At least, I compiled it on macOS 10.12 the other day. Have you made sure to update Homebrew, so that you use the latest version of ROOT?

$ brew update  
$ brew install root6

**Comment by alexpearce** [comment]
_Comment № 24 originally by Mathias at 2016-10-28 01:47:11 UTC_.

Hi Alex. How exactly do I edit that file (.bashrc) on bash? I tried using vi, but after inserting the line I couldn't get out again. And when I try using the root libraries, my compiler complains that it can't find the header files (such as TApplication.h), even though I'm using root-config --cflags --libs

**Comment by alexpearce** [comment]
_Comment № 25 originally by Alex Pearce at 2016-10-28 15:33:15 UTC, replying to [a comment by Mathias at 2016-10-28 01:47:11 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781514957)_.

You can use any text editor you like. To edit a file with a graphical application from the command line, you can do, for example:  


$ open -a Atom ~/.bashrc  
This would open the file in the [Atom editor](https://atom.io/ "https://atom.io/").

You don't *need* to add the line to your bashrc. You can just run the command in every new shell that you want to use ROOT stuff in. Adding the command to your bashrc is a convenience.

I'm able to compile this test program:  


#include <tapplication.h>  
  
int main(int argc, char *argv[])  
{  
 return 0;  
}  
  
  
(for some reason the comments are lowercasing ‘TApplication.h’ to ‘tapplication.h’) saved in a file called foo.cxx sing this command:  


clang++ `root-config --cflags --libs` -o foo foo.cxx

**Comment by alexpearce** [comment]
_Comment № 26 originally by rose at 2017-02-08 01:35:20 UTC_.

Tried this with the most recent version of root (6.06.04) and I can't access root while running python with import ROOT...anyone else having this error?

I don't have conda installed and I've defined ROOTSYS, PYTHONPATH, LD\_LIBRARY, DYLD\_LIBRARY.

**Comment by alexpearce** [comment]
_Comment № 27 originally by Alex Pearce at 2017-02-08 08:34:39 UTC, replying to [a comment by rose at 2017-02-08 01:35:20 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781515024)_.

What's the error message you get when trying import ROOT? Just the usual ImportError: No module named ROOT?

Check the value of your PYTHONPATH variable. The folder it points to should contain a file called ROOT.py.

**Comment by alexpearce** [comment]
_Comment № 28 originally by juha k at 2017-04-12 10:18:55 UTC_.

Hi Alex

Thanks for guide.

After few copypaste I have root running on osx sierra 10.12.4

**Comment by alexpearce** [comment]
_Comment № 29 originally by Andrew Hardy at 2017-06-01 17:27:07 UTC_.

Do you have a guide available for downloading ROOT using linuxbrew? Following your directions falls short because I seem to be missing some directory

**Comment by alexpearce** [comment]
_Comment № 30 originally by Alex Pearce at 2017-06-02 07:13:42 UTC, replying to [a comment by Andrew Hardy at 2017-06-01 17:27:07 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781515103)_.

I haven't used linuxbrew but I can try it. What commands are you running, and what error(s) do you get?

**Comment by alexpearce** [comment]
_Comment № 31 originally by Tahereh Niknejad at 2017-06-12 12:10:41 UTC_.

Hi Alex,

Thank you for the instruction. I'm compiling a software with ROOT enabled.  
During the compilation I encountered this error:  
"ROOT requires support for C++11 or higher."  
I searched a bit on internet and found out that I need to reconfigure root with cxx11. Can you help me how to do that?  
My Mac is running OS X Yosemite, version 10.10.5.  
gcc and Xcode are updated to the latest version.

**Comment by alexpearce** [comment]
_Comment № 32 originally by Pedro Rossini Sardelich at 2017-07-24 04:18:33 UTC_.

Hi Alex,

I've just downloaded root following this steps and everything was fine. But, when I try to run some program, most of the times I got the following error: "symbol.ttf not found". Can you help me?

Thank you a lot.

**Comment by alexpearce** [comment]
_Comment № 33 originally by Alex Pearce at 2017-07-26 14:42:54 UTC, replying to [a comment by Pedro Rossini Sardelich at 2017-07-24 04:18:33 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781515185)_.

I've not seen that issue, but it appears to be a [known problem with the latest Homebrew build](https://root-forum.cern.ch/t/latest-root6-from-homebrew-cannot-find-fonts-and-icons/25562/10 "https://root-forum.cern.ch/t/latest-root6-from-homebrew-cannot-find-fonts-and-icons/25562/10"). The posts in the [thread](https://root-forum.cern.ch/t/latest-root6-from-homebrew-cannot-find-fonts-and-icons/25562/10 "https://root-forum.cern.ch/t/latest-root6-from-homebrew-cannot-find-fonts-and-icons/25562/10") seem to have a fix.

(I think you're already in that thread, but I'll post this to help others.)

**Comment by alexpearce** [comment]
_Comment № 34 originally by Irfan at 2017-12-17 14:38:21 UTC_.

hi Alex very nice info to install but in my case this did not word  
$(brew --prefix root6)/libexec/[thisroot.sh](http://thisroot.sh "thisroot.sh") . No such file or directory  
this error how to remove

**Comment by alexpearce** [comment]
_Comment № 35 originally by Alex Pearce at 2017-12-17 14:46:40 UTC, replying to [a comment by Irfan at 2017-12-17 14:38:21 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781515240)_.

Hi Irfan. The command might have changed, can you try this instead?  


. $(brew --prefix)/bin/thisroot.sh

**Comment by alexpearce** [comment]
_Comment № 36 originally by Irfan at 2017-12-17 15:10:17 UTC, replying to [a comment by Alex Pearce at 2017-12-17 14:46:40 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781515269)_.

Yes i tried this. And it did not said anything and take me to next line so does it means it is done ?

**Comment by alexpearce** [comment]
_Comment № 37 originally by Alex Pearce at 2017-12-17 15:11:44 UTC, replying to [a comment by Irfan at 2017-12-17 15:10:17 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781515299)_.

Yep! This command doesn't output anything on success. You can check the value of the ROOTSYS environment variable; if the script worked then it shouldn't be empty.

echo $ROOTSYS

**Comment by alexpearce** [comment]
_Comment № 38 originally by Irfan at 2017-12-17 15:14:46 UTC, replying to [a comment by Alex Pearce at 2017-12-17 15:11:44 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/25#issuecomment-781515325)_.

Ok thanks a lot.

**Comment by alexpearce** [comment]
_Comment № 39 originally by Lakshya Malhotra at 2018-01-27 16:46:17 UTC_.

Hi Alex,

Thanks for this wonderful guide.   
Can you please explain how to include the root libraries in the Apple's IDE xcode?

**Comment by alexpearce** [comment]
_Comment № 40 originally by Henry Schreiner at 2018-03-15 12:50:45 UTC_.

Update: ROOT is now in the core homebrew tap (and homebrew science is dead), and the default ROOT now is version 6. So `brew install root` is all you need now.
